### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by glebenko22**
I wrote a description

### CODE REVIEW

**Comment by yanlukashevich** [comment]
hello who are you at all?

**Comment by yanlukashevich** [comment]
and what are you want

**Comment by glebenko22** [comment]
my name is Gleb and i wont help you.

**Comment by yanlukashevich** [comment]
### this is maybe heding text 
Ok, I understand how work this conversation.**this is bold text** and ### this is heading text
a little more experimentation. ### but heading text not add in middle of string _it is italic text_

> i don't know what it mean

`#include <stdio.h>
int main(){
scanf("",&);
}
`
`hello`
@glebenko22 #2

**Review by yanlukashevich — APPROVED** [review]
perfect

**Pull request merged**
